CREATE OR REPLACE FUNCTION get_top_limit()
RETURNS DECIMAL
LANGUAGE PLPGSQL
AS $$
DECLARE
	Q1 REAL := 0.0;
	Q3 REAL := 0.0;
	IQR REAL := 0.0;
	-- top_limit REAL := 0.0;
BEGIN
	Q1 := PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY total) FROM invoice;
	Q3 := PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY total) FROM invoice;

	IQR := Q3 - Q1;
	RETURN Q3 + (IQR * 1.5);
END
$$;